import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#007BFF',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  titulo1:{
    color: 'white',
    fontSize: 30,
    fontWeight: 'bold',
    top: -30,
  },
  input: {
    width: 250,
    height: 45,
    borderRadius: 5,
    marginVertical: 10,
    borderColor: 'grey',
    fontSize: 16,
    color: '#333',
    padding: 10,
    fontSize: 17,
    backgroundColor: 'white',
    marginLeft: 15,
  },
  drop:{
    width: 250,
    height: 45,
    borderRadius: 5,
    marginVertical: 10,
    borderColor: 'grey',
    fontSize: 16,
    color: '#333',
    padding: 10,
    fontSize: 17,
    backgroundColor: 'white',
    marginLeft: 5,
  },
  btnText1: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center', 
  },
  btn1: {
    backgroundColor: 'black',
    padding: 10,
    margin: 10,
    borderRadius: 10,
    width: 150,
    marginLeft: 8,
    top: 70 ,

  },
  btnText2: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center', 
  },
  btn2: {
    backgroundColor: 'black',
    padding: 10,
    margin: 10,
    borderRadius: 10,
    width: 150,
    marginLeft: 8,
    top: 50 ,
  },
});
