import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
    ContPerfil: {
        top: -200,
        backgroundColor: '#007BFF',
        height: 190,
        width: 400,
        borderRadius: 30,
        textAlign: 'center',
    },
    TextPerfil: {
        textAlign: 'center',
        top: 120,
        fontSize: 30,
        fontWeight: 'bold',
        color: 'white'
    },
    PerfilUsuario: {
        color: '#007BFF',
        fontWeight: 'bold',
        fontSize: 22,
        marginRight: 120,
        top: -110,
    },
    ContNombre: {
        top: -100,
        backgroundColor: '#007BFF',
        color: 'white',
        fontWeight: 'bold',
        width: 300,
        height: 40,
        borderRadius: 30,
        textAlign: 'center',
        fontSize: 22,
    },
    ContTelefono: {
        color: '#007BFF',
        fontWeight: 'bold',
        fontSize: 22,
        marginRight: 166,
        top: -30,
    },
    Telefono: {
        top: -20,
        backgroundColor: '#007BFF',
        color: 'white',
        fontWeight: 'bold',
        width: 300,
        height: 40,
        borderRadius: 30,
        textAlign: 'center',
        fontSize: 22,
    },
    ContDNI: {
        color: '#007BFF',
        fontWeight: 'bold',
        fontSize: 22,
        marginRight: 270,
        top: -70,
    },
    DNI: {
        top: -60,
        backgroundColor: '#007BFF',
        color: 'white',
        fontWeight: 'bold',
        width: 300,
        height: 40,
        borderRadius: 30,
        textAlign: 'center',
        fontSize: 22,
    },
    BtnText1: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    Btn1: {
        backgroundColor: '#007BFF',
        padding: 10,
        margin: 10,
        borderRadius: 10,
        width: 150,
        marginLeft: 180,
        top: 83,
    },
    BtnText2: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    Btn2: {
        backgroundColor: '#007BFF',
        padding: 10,
        margin: 10,
        borderRadius: 10,
        width: 150,
        marginRight: 180,
        top: 19.3,
    }
})